import type {Metadata, Viewport} from "next";
import "../globals.css";
import Navbar, {NavItem} from "@/components/Navbar/Navbar";
import {Roboto, Rubik_Bubbles} from 'next/font/google'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const rubik_bubbles = Rubik_Bubbles({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-rubik_bubbles',
});

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-roboto',
});

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  // Also supported by less commonly used
  // interactiveWidget: 'resizes-visual',
}
export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode,
}>) {
  const navItem: NavItem[] = [
    {id: 'signup', title: 'Signup', route: '/signup', svgIcon: <div>Signup</div>},
    {id: 'login', title: 'Login', route: '/login', svgIcon: <div>Login</div>},
  ]

  return (
    <html lang="en" className={`h-full`}>
    <body className={`pb-14 h-full bg-base-100 ${rubik_bubbles.variable} ${roboto.variable}`}>
    <div id="modal-root"></div>
    <div className="flex flex-col min-h-full font-roboto">
      <div className={"flex justify-center items-center z-10"}>
        <Navbar navItem={navItem} loggedInState={false}/>
      </div>
      {children}
    </div>
    </body>
    </html>
  );
}
