import type {Metadata} from "next";
import "../globals.css";
import Navbar, {NavItem} from "@/components/Navbar/Navbar";
import {logout} from "@/app/(authenticated)/actions";
import {Archive, Calendar, CheckSquare, Plus} from "react-feather";
import {Roboto, Rubik_Bubbles} from "next/font/google";
import {Viewport} from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const rubik_bubbles = Rubik_Bubbles({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-rubik_bubbles',
});

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-roboto',
});

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
}

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode,
}>) {
  const navItem: NavItem[] = [
    {id: 'tasks', title: 'Tasks', svgIcon: <CheckSquare/>, route: '/'},
    {id: 'archive', title: 'Archive', svgIcon: <Archive/>, route: '/archive'},
    {id: 'calender', title: 'Calender', svgIcon: <Calendar/>, route: '/calender'},
    {
      id: 'add',
      title: 'Add',
      svgIcon: <Plus/>,
      route: '/new',
      className: 'bg-neutral-600 hover:scale-150 transition-all ease-in-out duration-200'
    }
  ]

  return (
    <html lang="en" className={` ${rubik_bubbles.variable} ${roboto.variable} mb-20`}>
    <body className="sm:pt-12 sm:px-14 px-4 pt-4 h-full font-roboto bg-neutral-50">
    <div id="modal-root"></div>
    <Navbar navItem={navItem} onLogOut={logout} loggedInState={true}/>
    <div className="flex flex-col min-h-full mb-24 sm:16">
      {children}
    </div>
    </body>
    </html>
  );
}
