import type {Metadata} from "next";
import "./globals.css";
import Navbar, {NavItem} from "@/components/Navbar/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode,
}>) {

  const navItem: NavItem[] = [
    {title: 'Home', route: '/'},
    {title: 'Tasks', route: '/tasks'},
    {title: 'Edit', route: '/edit'},
    {title: 'Calender', route: '/calender'}
  ]

  return (
    <html lang="en" className="h-full">
    <body className="pt-12 pb-14 pl-14 pr-14 h-full">
    <div className="flex flex-col min-h-full">
      <div className={"flex justify-center items-center mb-3 h-12"}>
        <Navbar navItem={navItem}/>
      </div>
      {children}
    </div>
    </body>
    </html>
  );
}
